### ISSUE TITLE
 [2023-05-22 21:16:15,273][go-cqhttp/WARNING] PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail.

### ISSUE THREAD

**Issue by frocysayori** [Syan-Lin/CyberWaifu#12]
原先的问题在我删除了文件之后，重新按照步骤安装了一次后解决了
在过程中遇到过缺少库的问题，即使运行了pip install -r requirements.txt也没有解决，后来在anaconda3里面的envs中相应环境里的site-packages，把requirements.txt复制了过来又运行了一次，解决了库的问题
可是后来又遇到了如上的问题，显示到这一行就没有动静了，在qq机器人里能收到消息，可是没有消息的输出
请问各位大佬该怎么解决呢...

**Comment by Syan-Lin** [comment]
这是后台打印编码的问题，不影响使用

**Comment by frocysayori** [comment]
> 这是后台打印编码的问题，不影响使用

哦哦，可是当时出那个问题的时候我也没法用...那应该是因为其他地方弄错了，现在出现的是这个
PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail.
请问该怎么办呢

**Comment by frocysayori** [comment]
> > 这是后台打印编码的问题，不影响使用
> 
> 哦哦，可是当时出那个问题的时候我也没法用...那应该是因为其他地方弄错了，现在出现的是这个 PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail. 请问该怎么办呢

非常感谢大佬的指点，在我重新设置了qqbot中的config后解决了，感谢每一个辛勤付出的程序员

**Comment by yushuosun** [comment]
> > > 这是后台打印编码的问题，不影响使用
> > 
> > 
> > 哦哦，可是当时出那个问题的时候我也没法用...那应该是因为其他地方弄错了，现在出现的是这个 PyCqBot: go-cqhttp 警告 Protocol -> device lock is disable. http api may fail. 请问该怎么办呢
> 
> 非常感谢大佬的指点，在我重新设置了qqbot中的config后解决了，感谢每一个辛勤付出的程序员

我也遇到了同样的问题，请问你具体是如何设置qqbot中的config呢？
