### ISSUE TITLE
token计算方式修改意见

### ISSUE THREAD

**Issue by tomeishinzou** [Syan-Lin/CyberWaifu#19]
我注意到在调用claude的写法中，似乎仍然使用了openAI的api key对token进行统计，而有些用户正是因为没有openAI的api key转而使用Claude模型的，因此我建议将这一部分的写法修改为使用openAI官方提供的token处理py库，详情请参考：
[tiktoken on github](https://github.com/openai/tiktoken)

**Comment by Syan-Lin** [comment]
Langchain计算Token并不需要OpenAI的API Key，实际上它计算的方式就是基于tiktoken，这一点和OpenAI提供的方法是一致的。`Claude.py`的代码中你会看到实际上传入的是一个无效的API Key，这是一个没有Claude Token计算方式的一个折衷方案，后续Langchain支持Claude之后应该会有配套的计算方法。

**Comment by tomeishinzou** [comment]
确实，不过我很喜欢Claude那一部分的处理方式，实际上是处理还没对langchain做适配的模型如何手动制作api的一种范例，学习（抄）了
