### ISSUE TITLE
can't boost up the project

### ISSUE THREAD

**Issue by dupeiran001** [Syan-Lin/CyberWaifu#2]
program panic when running `python ./main.py`

error message is listed:

```shell
Exception in thread go-cqhttp:
Traceback (most recent call last):
  File "/Users/dpr/anaconda3/envs/CyberWaifu/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/dpr/anaconda3/envs/CyberWaifu/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/dpr/anaconda3/envs/CyberWaifu/lib/python3.10/site-packages/pycqBot/cqHttpApi.py", line 335, in cqhttp_start
    shell_msg = subp.stdout.readline().decode("utf-8").strip()
UnboundLocalError: local variable 'subp' referenced before assignment
^C
```

I'm not familiar with python so if I've messed something up?

**Comment by Syan-Lin** [comment]
邮件我已经收到，稍后查看！（自动回复）

**Comment by Syan-Lin** [comment]
Please list the steps of your installation, so I can recurrent the promblem and solve this.

**Comment by Syan-Lin** [comment]
> program panic when running `python ./main.py`
> 
> error message is listed:
> 
> ```shell
> Exception in thread go-cqhttp:
> Traceback (most recent call last):
>   File "/Users/dpr/anaconda3/envs/CyberWaifu/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
>     self.run()
>   File "/Users/dpr/anaconda3/envs/CyberWaifu/lib/python3.10/threading.py", line 953, in run
>     self._target(*self._args, **self._kwargs)
>   File "/Users/dpr/anaconda3/envs/CyberWaifu/lib/python3.10/site-packages/pycqBot/cqHttpApi.py", line 335, in cqhttp_start
>     shell_msg = subp.stdout.readline().decode("utf-8").strip()
> UnboundLocalError: local variable 'subp' referenced before assignment
> ^C
> ```
> 
> I'm not familiar with python so if I've messed something up?

Please list the steps of your installation, so I can recurrent the promblem and solve this.

**Comment by dupeiran001** [comment]
ok, here it is

``` bash
# conda init
git clone https://github.com/Syan-Lin/CyberWaifu
cd CyberWaifu
conda create --name CyberWaifu python=3.10.10
conda activate CyberWaifu
pip install -r requirements.txt

# go-cqhttp compile
# they haven't provide a release for macOS, so I have to build it myself
cd qqbot
mkdir src
cd src
git clone https://github.com/Mrs4s/go-cqhttp.git
cd go-cqhttp
go build -ldflags "-s -w -extldflags '-static'"
cp ./cq-http ../../ # that's root/qqbot/cq-http

cd ../../../ # that is the root

# and I've installed ffmpeg already

# config.ini setting
cp template.ini config.init

# I only add my OpenAI API key in it 

python ./main.py

```

by the way, system is `macOS 13.3.1 with M1 Pro chips`

**Comment by Syan-Lin** [comment]
> 
I see the promblem, it's caused by the library `pycqBot`.
In the line 326 of `pycqBot/cqHttpApi.py`, there is a function:
```python
"""
运行 go-cqhttp 并连接 websocket 会话
"""
def cqhttp_start():
    self._set_config(go_cqhttp_path)
    plat = platform.system().lower()
    if plat == 'windows':
        subp = subprocess.Popen("cd %s && .\go-cqhttp.exe -faststart" % go_cqhttp_path, shell=True, stdout=subprocess.PIPE)
    elif plat == 'linux':
        subp = subprocess.Popen("cd %s && ./go-cqhttp -faststart" % go_cqhttp_path, shell=True, stdout=subprocess.PIPE)

    while self._start_in:
        shell_msg = subp.stdout.readline().decode("utf-8").strip()
        if shell_msg.strip() == "":
            continue

        if "CQ WebSocket 服务器已启动" in shell_msg:
            self._websocket_start_in = False
        
        if print_error and "INFO" not in shell_msg:
            self.cqhttp_log_print(shell_msg)
        elif not print_error:
            self.cqhttp_log_print(shell_msg)
```
The `plat` does not support macOS, I guess you can add a `elif` to make a shell command for this to work.

BTW, you can jump to `pycqBot/cqHttpApi.py` by line 88 in `qqbot/qqbot.py` with the `start()` function.
