### ISSUE TITLE
内容裁切方式意见

### ISSUE THREAD

**Issue by tomeishinzou** [Syan-Lin/CyberWaifu#20]
first sentence裁切内容的方式有点迷，希望以后可以改进一下

![image](https://github.com/Syan-Lin/CyberWaifu/assets/69448420/d2c3bbcd-8fa5-4f71-8226-93a3746ad597)

![image](https://github.com/Syan-Lin/CyberWaifu/assets/69448420/9241daec-3161-4465-8729-64c3aacbed30)

**Comment by Syan-Lin** [comment]
具体是迷在哪里。。。我只能猜测你是没收到完整的回复？因为我在使用Claude的时候也有遇到过，但这部分是通过slack的api，实际上是一种网页内容的抓取。在消息过长的时候api获得的数据是分段的，然后会导致这种问题。但是Claude后续应该会给API，这部分就不准备解决了，后续直接换API就不会有这种问题了。
