### ISSUE TITLE
机器人不回复消息

### ISSUE THREAD

**Issue by nanqisang777** [Syan-Lin/CyberWaifu#22]
作者大大您好，我是一名0基础的小白，在研究了几个小时后部署了您的机器人，但是在我运行main.py之后，跳出cyberwaifu以及cqbot的字样之后，出现了一行警告代码：device lock is disable. http api may fail.
并且我给机器人发送任何消息，机器人都不会回复。我使用的是Claude的模型，token和bot-id都是正确的。
请问我该如何解决？期待您的答复。

**Comment by nanqisang777** [comment]
补充：我在单独运行cqbot时发现机器人可以正常收到消息，但是不能回复，这是否是cqbot的问题？

**Comment by nanqisang777** [comment]
再次补充：刚刚我查看了bot的日志，发现可以正常接收消息，那么应该是从收到消息往slack转发时出了问题....

**Comment by nanqisang777** [comment]
继续补充：打开qqbot文件中的qqbot.py文件时提示了报错：
Traceback (most recent call last):File"D:\QQ\CyberWaifu-main\qqbot\qqbot.py"，line 3，in <module>from waifu.Waifu import Waifu
ModuleNotFoundError: No module namedwaifu.

我想我已经离答案很近了，祝我好运吧

**Comment by nanqisang777** [comment]
后续：我发现并不是由于qqbot.py引起的问题，这样就又回到第三点了....头皮发麻

**Comment by yushuosun** [comment]
请问你解决了吗，我也遇到了同样的问题

**Comment by nanqisang777** [comment]
已经解决了。
我是打开了qqbot文件夹中的config.yml文件，在最下方severs里添加了下列代码：
- http: # HTTP 通信设置
      address: 0.0.0.0:5700 # HTTP监听地址
      timeout: 5      # 反向 HTTP 超时时间, 单位秒，<5 时将被忽略
      long-polling:   # 长轮询拓展
        enabled: false       # 是否开启
        max-queue-size: 2000 # 消息队列大小，0 表示不限制队列大小，谨慎使用
      middlewares:
        <<: *default # 引用默认中间件
      post:           # 反向HTTP POST地址列表
      #- url: ''                # 地址
      #  secret: ''             # 密钥
      #  max-retries: 3         # 最大重试，0 时禁用
      #  retries-interval: 1500 # 重试时间，单位毫秒，0 时立即
      #- url: http://127.0.0.1:5701/ # 地址
      #  secret: ''                  # 密钥
      #  max-retries: 10             # 最大重试，0 时禁用
      #  retries-interval: 1000      # 重试时间，单位毫秒，0 时立即



 - ws:
      # 正向WS服务器监听地址
      address: 0.0.0.0:8080
      middlewares:
        <<: *default # 引用默认中间件

希望能对其他有同样问题的人们有所帮助。

**Comment by nanqisang777** [comment]
其实就是在部署cqbot的时候同时部署http和正向web，这样应该就能解决了。
