### ISSUE TITLE
聊天就PyCqBot: expected string or b>lines 1336-1377/1377 (END)

### ISSUE THREAD

**Issue by ccc007ccc** [Syan-Lin/CyberWaifu#23]
昨天还是好的，今天就寄了

g_0/ERROR] PyCqBot: expected string or buffer                                      
g_0/INFO] PyCqBot: 开始！接收到信息: 你好
g_0/ERROR] PyCqBot: expected string or buffer
g_0/INFO] PyCqBot: 开始！接收到信息: 你好

g_0/ERROR] PyCqBot: expected string or buffer

**Comment by Syan-Lin** [comment]
貌似是回复的消息是空，导致这个问题，没有具体的复现步骤没法排查

**Comment by qcdg1** [comment]
@1492949083 老哥这个是怎么弄好的哇
