### ISSUE TITLE
联网搜索功能报错。

### ISSUE THREAD

**Issue by slot181** [Syan-Lin/CyberWaifu#24]
看起来好像是谷歌反爬了？
[run_on_private_msg_0/ERROR] PyCqBot: 403 Client Error: Forbidden for url: https://google.serper.dev/search?q=%E4%B8%8A%E5%8F%A4%E5%8D%B7%E8%BD%B45%EF%BC%8C%E4%B8%96%E7%95%8C%E6%98%AF%E4%BB%80%E4%B9%88%EF%BC%8C%E6%90%9C%E7%B4%A2&gl=cn&hl=zh-cn&num=20

**Comment by Syan-Lin** [comment]
用的是谷歌的API，不存在反爬的问题，应该是你API没设置好

**Comment by slot181** [comment]
感觉是号被谷歌封了，一注册就失效，麻了
