### ISSUE TITLE
机器人不回复

### ISSUE THREAD

**Issue by Prometheus-first** [Syan-Lin/CyberWaifu#6]
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/d62b45cc-46f7-4711-9302-1db815db00ac)

**Comment by Syan-Lin** [comment]
给出具体的复现步骤，否则无法解答

**Comment by Prometheus-first** [comment]
conda create -n waifu python=3.10.10创建好之后
安装了requirements.txt的依赖
然后把最新版gocqhttp下载了
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/d0b18f14-b8dd-4aac-a4bc-377729088209)
之后ffmpeg正确配置
记忆数据库向量计算模型也下载并且解压了
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/ba419da1-febe-4247-a715-6026729eb223)
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/39e891d1-47d4-4cbc-bca7-9ef94bf666eb)
之后config.ini内使用的是claude
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/66545ef8-a2fb-4946-ac1c-0fcedf49dda1)
运行之后的结果如下：
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/8cbf65b8-598f-479b-bafd-62ca68d43407)

提问机器人并无回复:
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/f50cda6a-cdba-4791-a4e9-7398ccdb19b4)

**Comment by Syan-Lin** [comment]
如果使用Claude，在网页端会看到输入和输出信息
![图片](https://github.com/Syan-Lin/CyberWaifu/assets/57340079/e6de1870-ee16-412d-abe9-9f2b28099bea)

**Comment by Prometheus-first** [comment]
这种东西可以清除吗：
![image](https://github.com/Syan-Lin/CyberWaifu/assets/80702346/c06bd374-5d2c-4a51-b399-ffb71c31e215)

**Comment by Prometheus-first** [comment]
跑通了，太牛了，预计什么时候上线群聊功能呢
