### ISSUE TITLE
现阶段使用claude时的一些小bug

### ISSUE THREAD

**Issue by holygodly** [Syan-Lin/CyberWaifu#9]
感谢作者大大分享，用了一天多，发现了几个小问题，跟您反应一下

1. **在使用搜索功能时，claude会直接输出搜索的tag**。比如，在问塞尔达相关问题的时候，就会直接输出它搜索过的关键词，这个问题在问一些需要网络搜索时的问题时时常发生（比如最近热门电影之类的）。（图裂是我pc qq的问题，与bug无关）
![image](https://github.com/Syan-Lin/CyberWaifu/assets/41179861/b0ba15af-fb23-455b-9ee5-90b7a732a30e)
![image](https://github.com/Syan-Lin/CyberWaifu/assets/41179861/563b2228-2723-4be5-8080-d03430e2ee8e)

2. 有时候会重复之前的对话（长句分成好几句话那种，批量重复）发生频率较低，十次对话可能有一次会这样，重启过bot所以没有截图。

3. 又是侯会有莫名其妙的输出，比如输出“[CQ:record,file=file:///G:\BOT\CyberWaifu\output.wav,magic=0,cache=1,proxy=1,timeout=0]”这种，在claude记录中没有，应该是bot自身问题。

4.我给bot模板设置成生活在国外，可是在回答的时候经常忘记它自己的所在地。 （在原设定上增加的设定，可能是设定过长导致有时候忘有时候又想起来了）

**Comment by holygodly** [comment]
具体在conda里运行的代码截图可能得等到下次遇到再截了。。。总之还是谢谢大大的机器人，玩的很开心哈哈哈

**Comment by Syan-Lin** [comment]
Claude 部分是通过 slack api 内容获取的，在消息过长时会发生分段发送的情况，机器人只会获取第一段的回复，这部分的内容通常是会重复的。目前并不打算解决（这部分实际上是其他人写的，我并不熟悉 slack api），Claude 这部分语言模型日后肯定会有更好的，我花精力解决这个问题很可能一个月之后就没用了。而且我本职比较忙，自己也在等更好的、成本更低的模型出来。

**Comment by holygodly** [comment]
chatgpt这一点会不会更好一点，之前用过，但是设定长一点就很费token。。。算了反正claude也是白嫖，有点小毛病也无所谓了哈哈哈哈
